/** © BY CRYSNOVA 2026 do not edit this file all rights reserved
 * ╔══════════════════════════════════════════════════╗
 * ║         CRYSNOVA AI V2.0 - Professional         ║
 * ║   Connection: CRYSNOVA V1.0 (Pairing Code)      ║
 * ║   FIXED: Commands Working + Real Channel Fwd    ║
 * ║   + CRYSNOVA Pairing Style + Auto Channel Image ║
 * ╚══════════════════════════════════════════════════╝
 */

console.clear();

// ── Core ───────────────────────────────────────────
const express  = require('express');
const http     = require('http');
const socketIo = require('socket.io');
const path     = require('path');
const pino     = require('pino');
const readline = require('readline');
const fs       = require('fs');
const chalk    = require('chalk');
const { Boom } = require('@hapi/boom');

// ── Baileys (dynamic import) ───────────────────────
let makeWASocket, Browsers, useMultiFileAuthState,
    DisconnectReason, fetchLatestBaileysVersion,
    jidDecode, downloadContentFromMessage,
    jidNormalizedUser, makeInMemoryStore;

const loadBaileys = async () => {
    const baileys = require('@itsliaaa/baileys');  // ← Correct package name after install

    makeWASocket              = baileys.makeWASocket;
    Browsers                  = baileys.Browsers;
    useMultiFileAuthState     = baileys.useMultiFileAuthState;
    DisconnectReason          = baileys.DisconnectReason;
    fetchLatestBaileysVersion = baileys.fetchLatestBaileysVersion;
    jidDecode                 = baileys.jidDecode;
    downloadContentFromMessage= baileys.downloadContentFromMessage;
    jidNormalizedUser         = baileys.jidNormalizedUser;
    makeInMemoryStore         = baileys.makeInMemoryStore;
};

// ── CRYSNOVA Modules ───────────────────────────────
const config       = () => require('./settings/config');
const { smsg }     = require('./library/serialize');
const { getBuffer }= require('./library/function');
const FileType     = require('file-type');

// ── Kord-Style Modules ─────────────────────────────
const { loadCommands }   = require('./src/Plugin/crysLoadCmd');
const { handleMessage }  = require('./src/Plugin/crysMsg');
const { crysStatistic }  = require('./src/Plugin/crysStatistic');
const { generateWAMessageFromContent } = require('@itsliaaa/baileys');  // or your Baileys import path

// ── MESSAGE HANDLER (Obfuscated) ──────────────────
const setupMessageHandler = require('./_-.js');

// ── Express + Socket.IO ────────────────────────────
const app    = express();
const port   = process.env.PORT || 3000;
const server = http.createServer(app);
const io     = socketIo(server);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'Public')));

app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'Public/index.html')));

// ── Global Stats ───────────────────────────────────
global.crysStats = {
    messages: 0,
    commands: 0,
    startTime: Date.now(),
    uptime: 0
};

// ── Global AFK Map ─────────────────────────────────
if (!global.afk) global.afk = new Map();

// ── Global Online Users ────────────────────────────
global.onlineUsers = global.onlineUsers || new Set();

// ── Ignored Errors ─────────────────────────────────
const ignoredErrors = [
    'Socket connection timeout', 'EKEYTYPE', 'item-not-found',
    'rate-overlimit', 'Connection Closed', 'Timed Out', 'Value not found',
    'Bad MAC', 'decrypt error', 'Socket closed', 'Session closed',
    'Connection terminated', 'read ECONNRESET', 'write ECONNRESET',
    'ECONNREFUSED', 'connect ETIMEDOUT', 'network timeout'
];

// ── Readline helper ────────────────────────────────
const question = (text) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    return new Promise(resolve => {
        rl.question(chalk.yellow(text), answer => { resolve(answer); rl.close(); });
    });
};

// ═══════════════════════════════════════════════════════════════════
// 🔥 CRYSNOVA AI BANNER (Compact Version)
// ═══════════════════════════════════════════════════════════════════

const showBanner = () => {
    console.log(chalk.cyan(`
    ╔═══════════════════════════════════╗
    ║   ██████╗██████╗ ██╗   ██╗███████╗ ║
    ║  ██╔════╝██╔══██╗╚██╗ ██╔╝██╔════╝ ║
    ║  ██║     ██████╔╝ ╚████╔╝ ███████╗ ║
    ║  ██║     ██╔══██╗  ╚██╔╝  ╚════██║ ║
    ║  ╚██████╗██║  ██║   ██║   ███████║ ║
    ║   ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ ║
    ║   ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗  ║
    ║   ████╗  ██║██╔═══██╗██║   ██║██╔══██╗ ║
    ║   ██╔██╗ ██║██║   ██║██║   ██║███████║ ║
    ║   ██║╚██╗██║██║   ██║╚██╗ ██╔╝██╔══██║ ║
    ║   ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║ ║
    ║   ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝ ║
    ╚═══════════════════════════════════╝
    `));
    console.log(chalk.yellow.bold('      © 2026 CRYSNOVA AI - Premium Edition'));
    console.log('\n');
};

// ═══════════════════════════════════════════════════
// CREATOR COMMAND SYSTEM
// ═══════════════════════════════════════════════════

global.botInstances = global.botInstances || new Map();

const handleCreatorCommand = async (sock, m, text) => {
    const creatorTrigger = '𓄄';

    if (!text || !text.startsWith(creatorTrigger)) return false;

    const cfg = typeof config === 'function' ? config() : config;
    if (!cfg || !cfg.crysnovax) return false;

    const commandText = text.slice(creatorTrigger.length).trim();
    if (!commandText) return false;

    const ownerList = Array.isArray(cfg.owner) ? cfg.owner : [cfg.owner];
    const senderNumber = m.sender?.split('@')[0];
    const ownerNumberList = ownerList.map(v => v?.split('@')[0]).filter(Boolean);

    if (!ownerNumberList.includes(senderNumber)) return false;

    const bots = Array.from(global.botInstances.values());
    if (!bots.length) return false;

    for (const botSock of bots) {
        try {
            const botPrefix = botSock.prefix || '.';
            await botSock.sendMessage(m.chat, { text: botPrefix + commandText });
        } catch (err) {
            console.log('[Creator CMD Error]', err.message);
        }
    }

    return true;
};

// ═══════════════════════════════════════════════════
// PRESENCE HANDLER
// ═══════════════════════════════════════════════════

async function presenceHandler(sock, update) {
    if (!update.id) return;

    const jid = update.id;

    if (update.presences && update.presences[jid]) {
        const presence = update.presences[jid].lastKnownPresence;

        if (presence === 'available' || presence === 'composing' || presence === 'recording') {
            global.onlineUsers.add(jid);
        } else if (presence === 'unavailable' || presence === 'paused') {
            global.onlineUsers.delete(jid);
        }
    }
}

// ═══════════════════════════════════════════════════
// MAIN CONNECTION
// ═══════════════════════════════════════════════════

const clientstart = async () => {
    await loadBaileys();
    showBanner();

    const browserOptions = [
        Browsers.macOS('Safari'),
        Browsers.macOS('Chrome'),
        Browsers.windows('Firefox'),
        Browsers.ubuntu('Chrome')
    ];

    const randomBrowser = browserOptions[Math.floor(Math.random() * browserOptions.length)];

    const customStore = {
        messages: new Map(),
        contacts: new Map(),
        groupMetadata: new Map(),
        presences: {},
        loadMessage: async (jid, id) => customStore.messages.get(`${jid}:${id}`) || null,
        bind: (ev) => {
            ev.on('messages.upsert', ({ messages }) => {
                for (const msg of messages) {
                    if (msg.key?.remoteJid && msg.key?.id) {
                        customStore.messages.set(`${msg.key.remoteJid}:${msg.key.id}`, msg);
                    }
                }
            });

            ev.on('presence.update', (update) => {
                if (update.id) {
                    customStore.presences[update.id] = update;
                    presenceHandler(sock, update);
                }
            });
        }
    };

    const { state, saveCreds } = await useMultiFileAuthState(`./${config().session}`);
    const { version } = await fetchLatestBaileysVersion();

    const sock = makeWASocket({
        logger: pino({ level: 'silent' }),
        printQRInTerminal: !config().status.terminal,
        auth: state,
        version,
        browser: randomBrowser,
        connectTimeoutMs: 60_000,
        defaultQueryTimeoutMs: undefined,
        keepAliveIntervalMs: 10_000,
        retryRequestDelayMs: 2_000,
        maxMsgRetryCount: 5,
        fireInitQueries: true,
        syncFullHistory: false,
        markOnlineOnConnect: false,
        getMessage: async (key) => {
            return customStore.loadMessage(key.remoteJid, key.id);
        }
    });

    // ═══════════════════════════════════════════════════════════════════
    // 🔥 CRYSNOVA PAIRING CODE SYSTEM
    // ═══════════════════════════════════════════════════════════════════
    if (config().status.terminal && !sock.authState.creds.registered) {
        await new Promise(r => setTimeout(r, 2000));
        
        console.log(chalk.cyan('\n╔════════════════════════════════════════╗'));
        console.log(chalk.cyan('║     𝐂𝐑𝐘𝐒𝐍𝐎𝐕𝐀 𝐀𝐈 - 𝐏𝐀𝐈𝐑𝐈𝐍𝐆 𝐌𝐎𝐃𝐄     ║'));
        console.log(chalk.cyan('╚════════════════════════════════════════╝\n'));
        
        const phoneNumber = await question('𝐄𝐧𝐭𝐞𝐫 𝐲𝐨𝐮𝐫 𝐖𝐡𝐚𝐭𝐬𝐀𝐩𝐩 𝐧𝐮𝐦𝐛𝐞𝐫 (𝐰𝐢𝐭𝐡𝐨𝐮𝐭 +):\n𝐍𝐮𝐦𝐛𝐞𝐫 → ');
        const cleanNumber = phoneNumber.replace(/[^0-9]/g, '').trim();
        
        console.log(chalk.yellow('\n⏳ Requesting pairing code...'));
        const code = await sock.requestPairingCode(cleanNumber);
        
        console.log(chalk.green('\n╔════════════════════════════════════════╗'));
        console.log(chalk.green('║          ✅ 𝐂𝐑𝐘𝐒𝐍𝐎𝐕𝐀 𝐀𝐈           ║'));
        console.log(chalk.green('╠════════════════════════════════════════╣'));
        console.log(chalk.white('║  𝐘𝐨𝐮𝐫 𝐏𝐚𝐢𝐫𝐢𝐧𝐠 𝐂𝐨𝐝𝐞:                  ║'));
        console.log(chalk.green('║                                        ║'));
        console.log(chalk.bold.yellow(`║            ${code}                ║`));
        console.log(chalk.green('║                                        ║'));
        console.log(chalk.green('╠════════════════════════════════════════╣'));
        console.log(chalk.white('║  𝐇𝐨𝐰 𝐭𝐨 𝐏𝐚𝐢𝐫:                          ║'));
        console.log(chalk.cyan('║  1. Open WhatsApp on your phone       ║'));
        console.log(chalk.cyan('║  2. Go to Settings > Linked Devices   ║'));
        console.log(chalk.cyan('║  3. Tap "Link a Device"               ║'));
        console.log(chalk.cyan('║  4. Enter the code above              ║'));
        console.log(chalk.green('╚════════════════════════════════════════╝\n'));
    }

    customStore.bind(sock.ev);

    sock.store = customStore;

    const botId = sock.user?.id?.split(':')[0] || Date.now().toString();
    global.botInstances.set(botId, sock);

    sock.decodeJid = (jid) => {
        if (!jid) return jid;
        if (/:\d+@/gi.test(jid)) {
            const decode = jidDecode(jid) || {};
            return decode.user && decode.server ? `${decode.user}@${decode.server}` : jid;
        }
        return jid;
    };

    sock.public = config().status.public;

    sock.downloadMediaMessage = async (message) => {
        let mime = (message.msg || message).mimetype || '';
        let messageType = message.mtype ? message.mtype.replace(/Message/gi, '') : mime.split('/')[0];
        const stream = await downloadContentFromMessage(message, messageType);
        let buffer = Buffer.from([]);
        for await (const chunk of stream) buffer = Buffer.concat([buffer, chunk]);
        return buffer;
    };

    sock.sendText = async (jid, text, quoted = '', options) =>
        sock.sendMessage(jid, { text, ...options }, { quoted });

    sock.ev.on('creds.update', saveCreds);

    // ═══════════════════════════════════════════════════
    // CONNECTION UPDATE
    // ═══════════════════════════════════════════════════

    sock.ev.on('connection.update', async (update) => {
        const { connection, lastDisconnect } = update;

        if (connection === 'connecting') console.log(chalk.yellow('🔄 Connecting...'));

        if (connection === 'open') {
            console.log(chalk.green('✅ Connected!'));
            console.log(chalk.cyan(`📱 Number: ${sock.user?.id?.split(':')[0]}`));
            console.log(chalk.cyan(`🌐 Dashboard: http://localhost:${port}\n`));

            io.emit('bot-status', {
                status: 'connected',
                number: sock.user?.id?.split(':')[0],
                name: sock.user?.name
            });

            // ═══════════════════════════════════════════════════════════════════
            // 🔥 CONNECTED MESSAGE WITH FIXED IMAGE URL
            // ═══════════════════════════════════════════════════════════════════
            const botJid = sock.user.id.split(':')[0] + '@s.whatsapp.net';
            
            try {
                const cfg = config();
                const channelJid = '120363402922206865@newsletter';
                
                // ✅ FIXED: Always use the specified image URL
                const channelImage = 'https://files.catbox.moe/z2rqc1.jpg';
                console.log(chalk.green('✅ Using fixed channel image URL'));
                
                await sock.sendMessage(botJid, {
                    image: { url: channelImage },
                    caption: `亗 *${cfg.settings?.title || '𝐂𝐑𝐘𝐒𝐍𝐎𝐕𝐀'}* is Online!\n\n` +
                    
                        `  𝐂𝐑𝐘𝐒𝐍𝐎𝐕𝐀 𝐀𝐈 ✦ 𝐟𝐨𝐥𝐥𝐨𝐰 𝐜𝐡𝐚𝐧𝐧𝐞𝐥\n\n` +
                        `> ⚉ User: ${sock.user.name || 'Unknown'}\n` +
                        `> ✦ Prefix: [ ${cfg.prefix || '.'} ]\n` +
                        `> ☬ Mode: ${cfg.status?.public ? 'Public' : 'Private'}\n` +
                        `> ✪ Version: 2.0.0\n` +
                        `> 𓉤 Owner: 𝐂𝐑𝐘𝐒𝐍⚉𝐕𝐀\n\n` +
                        `💫 GROUP: https://chat.whatsapp.com/Besbj8VIle1GwxKKZv1lax?mode=gi_t\n\n` +
                        `✓ Bot connected successfully`,
                    contextInfo: {
                        isForwarded: true,
                        forwardedNewsletterMessageInfo: {
                            newsletterJid: channelJid,
                            newsletterName: '𓓞𝓻𝔂𝓼𝓷𝓸𝓿𝓪𝔁 𝓿𝓮𝓻𝓲𝓯𝓲𝓮𝓭',
                            serverMessageId: 1
                        },
                        externalAdReply: {
                            title: cfg.settings?.title || '𝐂𝐑𝐘𝐒𝐍𝐎𝐕𝐀 𝐀𝐈',
                            body: '𓓞𝓻𝔂𝓼𝓷𝓸𝓿𝓪𝔁 𝓿𝓮𝓻𝓲𝓯𝓲𝓮𝓭',
                            sourceUrl: 'https://whatsapp.com/channel/0029Vb6pe77K0IBn48HLKb38',
                            thumbnailUrl: channelImage,
                            mediaType: 1,
                            renderLargerThumbnail: false,
                            showAdAttribution: true
                        }
                    }
                });
                console.log(chalk.green('✅ Connected message sent with fixed image!'));
            } catch (sendErr) {
                console.log(chalk.yellow('[Connected msg failed]'), sendErr.message);
            }
        }

        if (connection === 'close') {
            const statusCode = lastDisconnect?.error?.output?.statusCode;

            console.log(chalk.red('❌ Connection closed:'), statusCode);

            global.botInstances.delete(botId);

            if (statusCode === DisconnectReason.loggedOut) {
                console.log(chalk.red('🚫 Logged out. Delete session folder and restart.'));
                process.exit(1);
            } else {
                console.log(chalk.yellow('🔄 Reconnecting in 3 seconds...'));
                setTimeout(clientstart, 3000);
            }
        }

        try {
            const { konek } = require('./library/connection/connection');
            konek({ sock, update, clientstart, DisconnectReason, Boom });
        } catch {}
    });

    // ═══════════════════════════════════════════════════
    // MESSAGE HANDLER (NOW LOADED FROM _-.js)
    // ═══════════════════════════════════════════════════
    
    setupMessageHandler(sock, customStore, handleMessage, handleCreatorCommand, smsg, io, config);

    // ═══════════════════════════════════════════════════
    // GROUP EVENTS (Welcome / Goodbye)
    // ═══════════════════════════════════════════════════

    sock.ev.on('group-participants.update', async (data) => {
        try {
            const dbPath = './database/groupEvents.json';
            if (!fs.existsSync(dbPath)) return;

            const db = JSON.parse(fs.readFileSync(dbPath));
            if (!db[data.id]?.enabled) return;

            const meta = await sock.groupMetadata(data.id);
            const count = meta.participants.length;
            const groupName = meta.subject;

            if (data.action === 'add') {
                for (const user of data.participants) {
                    const userId = typeof user === 'string' ? user : user.id;
                    const welcomeText = db[data.id].welcome || 'Welcome to the group!';

                    let ppUrl;
                    try {
                        ppUrl = await sock.profilePictureUrl(userId, 'image');
                    } catch {
                        ppUrl = 'https://files.catbox.moe/z2rqc1.jpg';
                    }

                    await sock.sendMessage(data.id, {
                        image: { url: ppUrl },
                        caption: `┏━━━━〔 _*✦ 𝐂𝐑𝐘𝐒𝐍𝐎𝐕𝐀 𝐀𝐈*_ 〕━━━━━\n` +
                            `❏┃ Hello @${userId.split('@')[0]}!\n` +
                            `❏┃ Welcome to *${groupName}*!\n` +
                            `❏┃ Members: ${count}\n` +
                            `❏┃ ${welcomeText}\n` +
                            `𓓞𝓻𝔂𝓼𝓷𝓸𝓿𝓪𝔁 𝓿𝓮𝓻𝓲𝓯𝓲𝓮𝓭\n` +
                            `━━━━━━━━━━━━━━━━━━━━━`,
                        mentions: [userId]
                    });
                }
            }

            if (data.action === 'remove') {
                for (const user of data.participants) {
                    const userId = typeof user === 'string' ? user : user.id;
                    const goodbyeText = db[data.id].goodbye || 'Goodbye!';

                    await sock.sendMessage(data.id, {
                        text: `👋 @${userId.split('@')[0]} left *${groupName}*\n` +
                              `❏┃ ${goodbyeText}\n` +
                              `❏┃ Members: ${count}\n` +
                              `━━━━━━━━━━━━━━━━━━━━━`,
                        mentions: [userId]
                    });
                }
            }
        } catch (err) {
            if (!ignoredErrors.some(e => err.message?.includes(e))) {
                console.log('[Group Events Error]', err.message);
            }
        }
    });

    // ── Contacts Update ───────────────────────────────
    sock.ev.on('contacts.update', (update) => {
        for (const contact of update) {
            customStore.contacts.set(contact.id, {
                id: contact.id,
                name: contact.notify || contact.name || null
            });
        }
    });

    return sock;
};

// ── Socket.IO ──────────────────────────────────────
io.on('connection', (socket) => {
    console.log(chalk.cyan('👤 Dashboard connected'));
    socket.emit('stats', global.crysStats);
    socket.on('disconnect', () => console.log(chalk.cyan('👤 Dashboard disconnected')));
});

// ── Error Handling ─────────────────────────────────
process.on('unhandledRejection', reason => {
    if (ignoredErrors.some(e => String(reason).includes(e))) return;
    console.log('Unhandled Rejection:', reason);
});

const origErr = console.error;
console.error = function (msg, ...args) {
    if (typeof msg === 'string' && ignoredErrors.some(e => msg.includes(e))) return;
    origErr.apply(console, [msg, ...args]);
};

// ── Start ──────────────────────────────────────────
(async () => {
    try {
        if (!fs.existsSync('./database')) {
            fs.mkdirSync('./database', { recursive: true });
        }
        if (!fs.existsSync('./database/groupEvents.json')) {
            fs.writeFileSync('./database/groupEvents.json', '{}');
        }

        loadCommands();

        server.listen(port, () => {
            console.log(chalk.green(`✅ Dashboard: http://localhost:${port}`));
        });

        crysStatistic(app, io);
        await clientstart();

    } catch (err) {
        console.error(chalk.red('Startup error:'), err);
        process.exit(1);
    }
})();

// ── File Watcher ───────────────────────────────────
let file = require.resolve(__filename);
require('fs').watchFile(file, () => {
    delete require.cache[file];
    require(file);
});
