//© by crysnvax 2026 please do not edit this file use as it is 
module.exports = {
  command: 'info',
  alias: ['about', 'botinfo'],
  description: 'Show bot and owner details',
  category: 'owner',

  execute: async (sock, m, { reply }) => {
    try {
      const owner = 'https://wa.me/2348077528901'; 
      const repo = 'https://github.com/crysnovax/CRYSNOVA-AI'; 
      const web = 'https://soloist.ai/crysnova-designs'; 
      const creator = 'CRYSNOVAX'; 
      const channel = 'https://whatsapp.com/channel/0029Vb6pe77K0IBn48HLKb38'
      const group = 'https://chat.whatsapp.com/Besbj8VIle1GwxKKZv1lax?mode=gi_t'
      const infoText = `
╭───〔 ☬ CRYSN⚉VA BOT INFO ☬ 〕───╮
│
│ 👑 Creator: ${creator}
│ 📱 Owner WhatsApp: ${owner}
│ 📦 Repository: ${repo}
│ 🌐 Website: ${web}│  
| 👾 WhatsApp group ${group}
|🔊 channel: ${channel}
╰───────────────────────────────╯
`;

      await reply(infoText);
    } catch (err) {
      console.error('Info plugin error:', err);
      await reply('Failed to fetch info. Try again.');
    }
  }
};
