module.exports = {
    name: 'story',
    alias: ['advai', 'smartgen', 'aipro'],
    desc: 'Advanced AI text generation with modes',
    category: 'AI',

    execute: async (sock, m, { args, reply }) => {
        try {
            if (!args.length) {
                return reply(`🧠 Usage:
.story <text>
.story creative <text>
.story short <text>
.story long <text>`);
            }

            let length = 'medium';
            let isCreative = false;

            const flags = ['creative', 'short', 'medium', 'long'];
            let textArgs = [...args];

            while (textArgs.length > 0 && flags.includes(textArgs[0].toLowerCase())) {
                const flag = textArgs.shift().toLowerCase();
                if (['short', 'medium', 'long'].includes(flag)) length = flag;
                if (flag === 'creative') isCreative = true;
            }

            const text = textArgs.join(' ').trim();
            if (!text) return reply('_*𓄄 Give a valid text prompt*_');

            await sock.sendPresenceUpdate('composing', m.chat);

            let apiUrl = `https://apis.prexzyvilla.site/ai/advanced?text=${encodeURIComponent(text)}`;
            if (length !== 'medium') apiUrl += `&length=${length}`;
            if (isCreative) apiUrl += `&creative=true`;

            const res = await fetch(apiUrl);
            
            if (!res.ok) {
                return reply('_*⚉ API request failed*_');
            }

            const json = await res.json();
            
            // Deep search for any text content
            let result = null;
            
            // Check if json is string (direct response)
            if (typeof json === 'string') {
                result = json;
            } else {
                // Try all possible paths
                const paths = [
                    'story',
                    'result',
                    'response',
                    'text',
                    'output',
                    'message',
                    'content',
                    'data',
                    'answer',
                    'generated',
                    'reply'
                ];
                
                for (const path of paths) {
                    if (json[path]) {
                        result = json[path];
                        console.log(`[ADVANCED] Found at: ${path}`);
                        break;
                    }
                }
                
                // If still nothing, check nested objects
                if (!result && typeof json === 'object') {
                    const values = Object.values(json);
                    for (const val of values) {
                        if (typeof val === 'string' && val.length > 50) {
                            result = val;
                            console.log('[ADVANCED] Found string value:', val.slice(0, 50));
                            break;
                        }
                    }
                }
            }

            // Handle if result is still object
            if (typeof result === 'object' && result !== null) {
                const innerPaths = ['story', 'text', 'content', 'message', 'response'];
                for (const path of innerPaths) {
                    if (result[path]) {
                        result = result[path];
                        break;
                    }
                }
                if (typeof result === 'object') {
                    result = JSON.stringify(result);
                }
            }

            if (!result || result === '[object Object]' || result.length < 10) {
                console.log('[ADVANCED] Full response:', JSON.stringify(json));
                return reply('_*⚉ Could not extract text*_');
            }

            const message = `🧠 *ADVANCED AI*
☬ Length: ${length.toUpperCase()}${isCreative ? ' | Creative' : ''}

${result}

𓄄 Generated by Prexzy AI`;

            await reply(message);

        } catch (err) {
            console.error('[ADVANCED ERROR]', err);
            reply('_*✘ Failed to generate*_');
        }
    }
};

